CREATE DATABASE IF NOT EXISTS `site_db` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE site_db;

CREATE TABLE  `articles` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`title` VARCHAR( 100 ) NOT NULL ,
`description` VARCHAR( 100 ) NOT NULL 
) ENGINE = INNODB;

CREATE TABLE  `user` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`pseudo` VARCHAR( 100 ) NOT NULL ,
`name` VARCHAR( 100 ) NOT NULL ,
`firstname` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL
) ENGINE = INNODB;
