-- MySQL Script generated by MySQL Workbench
-- jeu. 27 janv. 2022 15:03:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site_db` ;
USE `site_db` ;

-- -----------------------------------------------------
-- Table `site_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imguser` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`pics` (
  `idphotos` INT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(255) NOT NULL,
  `authorname` VARCHAR(100) NOT NULL,
  `datephoto` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idphotos`),
  INDEX `fk_pics_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pics_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `site_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`commentaires` (
  `idcommentaire` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `pseudouser` VARCHAR(255) NOT NULL,
  `datecom` timestamp not null default current_timestamp on update current_timestamp,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idcommentaire`),
  INDEX `fk_commentaires_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `site_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imgarticle` VARCHAR(255) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `dateart` timestamp not null default current_timestamp,
  `dateedit` timestamp not null default current_timestamp on update current_timestamp,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `site_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_commentaires1`
    FOREIGN KEY (`id`)
    REFERENCES `site_db`.`commentaires` (`idcommentaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isAdmin` TINYINT NOT NULL,
  `isBanned` TINYINT NOT NULL,
  `isVerified` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_status_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_status_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `site_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
